language: python

python: "3.6.4"

before_install:
  - touch fake_key.pem
  - echo "- ./" > whitelist_external_dirs.yaml
  - mv travis_secrets.yaml secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c ./ --script check_config --info all

notifications:
  slack:
    rooms:
      - secure: sqBDpmmEpCcEI9Iq5wGefGMCuKq0SROxQU6nDxNUVmsypyejHnnI0JBTtWS/YDXc4TfFt6P4vPBqs35syTE3coL7gukKHtckwxSvu7Elu9SyWDFWaGReamLYtWg0bvBiBqyKNHsZiuO/hSBJzGELN9AIKX9bvKVyOdIdVzGc9a2Ga3CQflNERdJJ2pU5AoLWesrJOqK3C4AJro7ZCXbIs3wpPRLyMkjgtb5ZaMjJue8tdPqsln+F9zHMTtD57nyakjx2NhEomhO6Zm1qIhqGxCXYxOFqU54lSyXhUbs9OEcjuOQ0pe7cJfWO3LuYgxGzEYMcp5PXax6P7n7qYhwl9ISTWJsESJOlyRCC9TVeh1FwElV+uORzcz9eQId9sitJya08/8n8Q2deiNmXWJwvn/S/R1HKoKNxiJUTsJyi0pAgpyCevga9prS/osPzQqgAcfgrttcXfm8iGlC4WtEtdATOCjLPOj03mKJ4pAhbbVrV2fnus65+rnrY3LhOUqTZKQ+SwoLER38xkq5okAJqyTESOyfiVNqRK81s3ZXCoTWl/2lN/932hTYyFkVMmCUo6/uEyosT2wuSVd6J2Iicvu2/pF1GIWgzOVkwXx1pYfgrHT7I4J15uDJHZoQOE1vtM2F115DVfdAFUSoXMNZKxerRSZ6w3Tf25/tVvdfKtjc=
    on_success: always
    on_failure: always
    template:
      - "Build <%{build_url}|#%{build_number}> (`%{commit}`) of %{repository_slug} *%{result}*"
      - "Branch: %{branch}"
      - "> \"_%{commit_message}_\""
      - "Duration: %{duration}"
      - "Author: %{author}"