language: python

python: "3.6.4"

before_install:
  - echo -e "folder_watcher:\n  - folder: ./\n    patterns:\n      - '*.jpg'" > integrations/folder_watcher.yaml
  - touch fake_key.pem
  - echo "- ./" > whitelist_external_dirs.yaml
  - mv travis_secrets.yaml secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c ./ --script check_config --info all