- id: '1601131580025'
  alias: Helderheid speeltafel licht
  description: ''
  trigger:
  - device_id: 816d9dec000511eb9f615f5f6c622405
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: brightness_increase
    device_id: 7050692b000411eb91ec2fb3c942a174
    entity_id: light.speeltafel
    domain: light
  mode: single
- id: '1601131634994'
  alias: Speeltafel licht helderheid opvoeren
  description: ''
  trigger:
  - device_id: 816d9dec000511eb9f615f5f6c622405
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: brightness_increase
    device_id: 7050692b000411eb91ec2fb3c942a174
    entity_id: light.speeltafel
    domain: light
  mode: single
- id: '1601131651451'
  alias: Speeltafel licht helderheid omlaag
  description: ''
  trigger:
  - device_id: 816d9dec000511eb9f615f5f6c622405
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: brightness_decrease
    device_id: 7050692b000411eb91ec2fb3c942a174
    entity_id: light.speeltafel
    domain: light
  mode: single
- id: '1601131668890'
  alias: Speeltafel licht aan
  description: ''
  trigger:
  - device_id: 816d9dec000511eb9f615f5f6c622405
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  condition: []
  action:
  - type: turn_on
    device_id: 7050692b000411eb91ec2fb3c942a174
    entity_id: light.speeltafel
    domain: light
  mode: single
- id: '1601131683990'
  alias: Speeltafel licht uit
  description: ''
  trigger:
  - device_id: 816d9dec000511eb9f615f5f6c622405
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_off
  condition: []
  action:
  - type: turn_off
    device_id: 7050692b000411eb91ec2fb3c942a174
    entity_id: light.speeltafel
    domain: light
  mode: single
- id: '1601131761555'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - device_id: 816d9dec000511eb9f615f5f6c622405
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_off
  condition: []
  action:
  - type: turn_off
    device_id: 7050692b000411eb91ec2fb3c942a174
    entity_id: light.speeltafel
    domain: light
  mode: single
- id: '1636463200526'
  alias: Afval push notificatie
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      reminder_title: Afval buiten zetten
      reminder_message: 'Het volgende afval zal morgen opgehaald worden:'
      garbage_sensor_1: sensor.afvalwijzer_gft
      garbage_sensor_2: sensor.afvalwijzer_papier
      garbage_sensor_3: sensor.afvalwijzer_pmd
      garbage_sensor_4: sensor.afvalwijzer_restafval
- id: '1636463240454'
  alias: Garbage reminder
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      garbage_sensor_1: sensor.afvalwijzer_gft
      garbage_sensor_2: sensor.afvalwijzer_pmd
      garbage_sensor_3: sensor.afvalwijzer_papier
      garbage_sensor_4: sensor.afvalwijzer_restafval
- id: '1636463290243'
  alias: Garbage reminder
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      garbage_sensor_1: sensor.afvalwijzer_gft
      garbage_sensor_2: sensor.afvalwijzer_pmd
      garbage_sensor_3: sensor.afvalwijzer_papier
      garbage_sensor_4: sensor.afvalwijzer_restafval
