- platform: ffmpeg
  name: Carport
  input: !secret camera_carport_stream

- platform: ffmpeg
  name: Living
  input: !secret camera_living_stream

- platform: local_file
  file_path: /config/www/testbeeld.png
  name: Carport movement
