homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 10
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs: !include whitelist_external_dirs.yaml
  packages: !include_dir_named integrations

default_config:

discovery:
