homeassistant:
  name: De Draaikes 32
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /share
    - /config/www
  packages: !include_dir_named integrations

default_config:

# discovery: