- platform: yr

- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /
    - type: memory_use
    - type: processor_use

- platform: mqtt
  state_topic: "homeassistant/sensor/macminidiskspace"
  name: "Mac Mini diskspace"
  unit_of_measurement: "GB"
  value_template: "{{ value | multiply(0.000000001) | float | round(1) }}"
 

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, remove degree symbol below
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'