title: De Draaikes 32
resources: !include_dir_list lovelace/resources

views:
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/home.yaml
  - !include lovelace/views/music.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/statistics.yaml