title: !secret name
resources: 
  - url: /local/custom-cards/atomic_calendar.js
    type: module
  - url: /local/floorplan/floorplan-card.js?018
    type: js
  - url: https://unpkg.com/moment@2.24.0/moment.js
    type: js
  - url: /local/custom-cards/monster-card.js
    type: js
  - url: /local/custom-cards/weather-card-chart.js
    type: module
  - url: /local/custom-cards/auto-entities.js
    type: js
  - url: /local/custom-cards/battery-entity.js?v=0.1
    type: module
  - url: /local/custom-cards/card-tools.js
    type: js
  - url: /local/custom-cards/bar-card.js
    type: js
  - url: /local/custom-lovelace/custom-header/custom-header.js?v=0.0.1
    type: module
  - url: /local/custom-cards/mini-graph-card-bundle.js?v=0.9.2
    type: module
  - url: /local/custom-cards/bignumber-card.js
    type: module

background: var(--background)

custom_header:
  background: rgba(155, 155, 155, 0.25)
  compact_mode: true
  voice_hide: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

views:
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/home.yaml
  - !include lovelace/views/music.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/statistics.yaml