title: De Draaikes 32
resources:
  - type: module
    url: /local/custom-weather-card-chart.js
  - url: https://unpkg.com/moment@2.24.0/moment.js
    type: js
  - url: /local/floorplan/floorplan-card.js?017
    type: js

views:
  - title: Floorplan
    icon: mdi:floor-plan
    panel: true
    cards:
    - type: "custom:floorplan-card"
      entities:
        - light.woonkamer
        - light.bureau_2
        - light.speeltafel
        - light.keukenkast
        - light.keuken
        - binary_sensor.motion_sensor

  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: glance
        title: Sensoren
        entities:
          - binary_sensor.carport_sensor
          - binary_sensor.motion_sensor

      - type: entities
        title: Scenes
        show_header_toggle: false
        entities:
            - entity: scene.slapen
            - entity: scene.thuis
            - entity: scene.tv_kijken
            - entity: scene.weg

      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm

      - type: thermostat
        name: Thermostaat
        entity: climate.toon_thermostat

      - type: entities
        title: Lichten
        show_header_toggle: false
        entities:
            - entity: light.bureau_2
            - entity: light.woonkamer
            - entity: light.keuken
            - entity: light.speeltafel
            - entity: light.keukenkast
            # - entity: light.xmas_tree
            - entity: light.tuin_grondspots
            - entity: light.terrasoverkapping

      - type: entities
        title: Automatisering
        show_header_toggle: false
        entities:
            - entity: automation.alarm
            # - entity: automation.occupancy_simulator
            - entity: automation.tuinlicht_zonsondergang
            - entity: automation.tuinlicht_zonsopgang
            - entity: automation.thermostaat_aan_om_06_45
            - entity: automation.motion_detector_keuken
            - entity: automation.motion_detector_carport

      - type: 'custom:weather-card-chart'
        title: Weather
        mode: hourly
        weather:  weather.dark_sky

  - title: Muziek
    icon: mdi:music
    cards:
        - type: media-control
          entity: media_player.huiskamer

        - type: entities
          title: Volume
          show_header_toggle: false
          entities:
           - entity: input_number.google_home_volume

        - type: entities
          title: Radio zenders
          show_header_toggle: false
          entities:
            - entity: script.play_radio538
            - entity: script.play_radio_2
            - entity: script.play_100procentnl

  - title: Camera
    icon: mdi:video
    cards:
      - type: picture-entity
        name: Carport
        entity: camera.carport
        camera_image: camera.carport
        show_state: false

      - type: picture-entity
        name: Carport motion
        entity: camera.carport_movement
        camera_image: camera.carport_movement
        show_state: false

      - type: picture-entity
        name: Woonkamer
        entity: camera.living
        camera_image: camera.living
        show_state: false

      - type: entity-button
        name: Save carport stream
        entity: script.send_capture_command
        show_icon: false
        tap_action:
          action: call-service
          service: script.send_capture_command
          service_data:
            stream: carport

      - type: entity-button
        name: Save living stream
        entity: script.send_capture_command
        show_icon: false
        tap_action:
          action: call-service
          service: script.send_capture_command
          service_data:
            stream: living

  - title: Stats
    icon: mdi:chart-areaspline
    cards:
        - type: gauge
          name: PI HDD
          unit: GB
          entity: sensor.disk_use
          max: 32

        - type: gauge
          name: PI Memory
          unit: GB
          entity: sensor.memory_use
          max: 1024

        - type: gauge
          name: PI CPU
          unit: "%"
          entity: sensor.processor_use

        - type: gauge
          name: HDD Mac Mini
          unit: GB
          entity: sensor.mac_mini_diskspace
          max: 320

        - type: gauge
          name: PI CPU Tempareture
          unit: °C
          entity: sensor.cpu_temperature
          max: 70

        - type: history-graph
          title: Temperatuur
          entities:
            - climate.toon_thermostat
