---
# An automation that fires when there is movement registered by the carport camera.
#
# Trigger:
# - Watch for in the /share folder for newly created .jpg files
#
# Conditions:
# - Only when the alarm is armed for away.
# - And none of the devices are in proximity of the house
#
# Actions:
# - Update the `camera.carport_movement` camera (which is a still image camera) with the newly created file
# - Wait 2 seconds
# - Send a push notification that a motion is detected with the (still) camera image as an attachment
# - Send a telegram message with the photo
# - Record the carport camera for 30s
# - Turn on the carport 'motion' sensor for 30s

alias: Motion detector carport
initial_state: true
trigger:
  platform: event
  event_type: folder_watcher
  event_data:
    event_type: created

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    - condition: state
      entity_id: group.persons
      state: not_home

action:
  - service: camera.local_file_update_file_path
    data_template:
      entity_id: camera.carport_movement
      file_path: "{{ trigger.event.data.path }}"
  - delay: '00:00:02'

  # Push notification
  - service: notify.all
    data:
      title: Carport
      message: Beweging gedetecteerd!
      data:
        attachment:
          content-type: jpeg
          hide-thumbnail: false
        push:
          category: camera
        entity_id: camera.carport_movement
        
  # Slack
  - service: notify.slack
    data:
      message: "Er is beweging gedetecteerd bij de carport terwijl er niemand thuis is."

  # Telegram
  - service: telegram_bot.send_message
    data:
      title: "*Carport*"
      message: "Beweging gedetecteerd!"
      parse_mode: markdown

  - service: telegram_bot.send_photo
    data_template:
      file: "{{ trigger.event.data.path }}"

  # Record
  - service: script.turn_on
    entity_id: script.record_camera_carport

  # Carport sensor
  - service: mqtt.publish
    data: 
      topic: home-assistant/sensor/carport
      payload: 'ON'

  - delay: '00:00:30'

  - service: mqtt.publish
    data: 
      topic: home-assistant/sensor/carport
      payload: 'OFF'

