---
# Automation triggered by motion in the kitchen
#
# Trigger:
# - The `binary_sensor.kitchen` sensor triggers a motion not present
#
# Conditions:
# - The currently selected scene is 'tv'
# - The sun is below the horizon (the garden tree lights ar lit)
#
# Actions:
# - Turn off the kitchen lights

alias: Motion detector keuken
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.kitchen
  to: 'off'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.scene
      state: tv

    - condition: time
      after: '16:00:00'
      before: '09:00:00'

action:
  - service: light.turn_off
    entity_id: light.keuken
