---
# Automation triggered by motion in the kitchen
#
# Trigger:
# - The `binary_sensor.motion_sensor` sensor triggers a motion
#
# Conditions:
# - The currently selected scene is 'tv'
# - The sun is below the horizon (the garden tree lights ar lit)
#
# Actions:
# - Turn on the kitchen lights

alias: Motion detector keuken
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.kitchen
  to: 'on'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.scene
      state: tv

    - condition: state
      entity_id: light.tuin_grondspots
      state: 'on'

action:
  - service: light.turn_on
    entity_id: light.keuken
