---
# Automation triggered by motion in the kitchen
#
# Trigger:
# - The `binary_sensor.motion_sensor` sensor triggers a motion
#
# Conditions:
# - The currently selected scene is 'tv'
# - The sun is below the horizon (the garden tree lights ar lit)
#
# Actions:
# - Turn on the kitchen lights
# - Call the timer that will turn off the lights in the kitchen automatically

alias: Motion detector keuken
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor
  to: 'on'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.scene
      state: tv

    - condition: state
      entity_id: light.tuin_grondspots
      state: 'on'

action:
  - service: light.turn_on
    entity_id: light.keuken
  - service: timer.start
    entity_id: timer.motion_detector_timer
