---

alias: "Playtable on switch pressed once"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: speeltafel_on_off_switch
    event: 1002
action:
  - service: light.turn_on
    entity_id: light.keuken
  - service: input_boolean.turn_on
    entity_id: input_boolean.force_kitchenlight_on
