---

alias: "Playtable off switch pressed long"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: speeltafel_on_off_switch
    event: 2001
action:
  - service: light.turn_off
    entity_id: light.speeltafel