---

alias: "Playtable on switch pressed once"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: speeltafel_on_off_switch
    event: 1002
action:
  - service: light.turn_on
    entity_id: light.speeltafel
    data_template:
      brightness: >-
        {% if is_state('light.speeltafel', 'off') %}
        190
        {% else %}
        {{ states.light.speeltafel.attributes.brightness + 30 }}
        {% endif %}