---

alias: "Playtable off switch pressed once"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: speeltafel_on_off_switch
    event: 2002
action:
  - service: light.turn_off
    entity_id: light.keuken
  - service: input_boolean.turn_off
    entity_id: input_boolean.force_kitchenlight_on
