---

alias: "Playtable on switch pressed long"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: speeltafel_on_off_switch
    event: 1001
action:
  - service: light.turn_on
    entity_id: light.speeltafel
    data_template:
      brightness: "{{ ((states('input_number.default_brightness_playtable_light') | float) * 2.55) | round(0) | int }}"