---
# Automatically urn on the garden light spots 30 minutes before sunset.
# Only when we're at home.

alias: "Tuinlicht zonsondergang"
trigger:
  event: sunset
  platform: sun
  offset: "-00:30:00"

initial_state: true
action:
  - service: light.turn_on
    data:
      entity_id: light.voordeur
  - condition: or
    conditions:
      - condition: state
        entity_id: input_select.state
        state: home
  - service: light.turn_on
    data:
      entity_id: light.tuinverlichting

  - service: script.turn_on
    entity_id: script.log_notify
    data:
      variables:
        message: "De zon gaat onder, de tuinlichten worden aangezet"
