---
title: Instellingen
icon: mdi:cog-outline
visible:
  - user: 72ce68b0c06d44b4b735d77b62318880
  - user: 928f8da852104c3c8317e5b6b94a4562
cards:
  - type: entities
    title: Automatisering
    show_header_toggle: false
    entities:
        - entity: automation.alarm
        - entity: automation.ramen_en_deuren_open_laten_staan_melding
        # - entity: automation.occupancy_simulator
        - entity: automation.tuinlicht_zonsondergang
        - entity: automation.tuinlicht_zonsopgang
        - entity: automation.thermostaat_automatisch_aan
        - entity: automation.motion_detector_keuken
        - entity: automation.deurbel_ingedrukt

  - type: entities
    title: Standaard waardes
    show_header_toggle: false
    entities:
      - entity: input_number.default_brightness_dining_table
        name: Helderheid eettafel lampen
      - entity: input_number.default_brightness_playtable_light
        name: Helderheid speeltafel licht
      - entity: input_number.default_brightness_bay_window
        name: Helderheid erker licht
      - entity: input_number.default_temperature
        name: Temperatuur thuis
      - entity: input_number.default_volume_streaming
        name: Volume streaming
