---
# Turn on the thermostat and set it to 21 degees at 07:00
# This way the house will be warmed up around 07:15

alias: "Thermostaat automatisch aan"
initial_state: false
trigger:
  platform: time
  at: "07:00:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.state
      state: sleep
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.thermostat
      temperature: "{{ states('input_number.default_temperature') | float(1) }}"
