---
# Turn on the thermostat and set it to 21 degees at 06:45
# This way the house will be warmed up around 07:00

alias: "Thermostaat aan om 06:45"
initial_state: false
trigger:
  platform: time
  at: "06:45:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.state
      state: sleep
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.toon_thermostat
      temperature: 21.5
  - service: notify.slack
    data:
      message: "Het is 06:45, de thermostaat wordt op 21°C gezet"
