---
alias: Update Google Home volume
initial_state: true
trigger:
  platform: state
  entity_id: media_player.huiskamer
action:
  service: input_number.set_value
  data_template:
    entity_id: input_number.google_home_volume
    value: "{{ state_attr("media_player.huiskamer", "volume_level") | float(2) }}"
