---
alias: Update Google Home volume
initial_state: true
trigger:
  platform: state
  entity_id: media_player.huiskamer
action:
  service: input_number.set_value
  target:
    entity_id: input_number.temp_google_home_volume
  data:
    value: "{{ trigger.to_state.attributes.volume_level | float(2) }}"
