---
alias: Update garbage sensors every 15 minutes
initial_state: true
trigger:
    platform: time_pattern
    minutes: "/15"
action:
  - service: homeassistant.update_entity
    data:
      entity_id: sensor.garbage_organic

  - service: homeassistant.update_entity
    data:
      entity_id: sensor.garbage_other

  - service: homeassistant.update_entity
    data: 
      entity_id: sensor.garbage_paper