---
alias: Home assistant startup
initial_state: true
trigger:
    - platform: homeassistant
      event: start
action:
  - service: notify.slack
    data:
      message: "Ik ben weer opgestart!"
        
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% if is_state('input_select.scene', 'home') -%} script.turn_on_scene_thuis
        {%- elif is_state('input_select.scene', 'tv') -%} script.turn_on_scene_tv
        {%- elif is_state('input_select.scene', 'sleep') -%} script.turn_on_scene_sleep
        {%- else -%} script.turn_on_scene_gone {%- endif %}
