---
# Turn off the garden ground light spots 30 minutes after sunrise.
# They'll probably be off at that time, but scene triggers could have turned them on.

alias: "Tuinlicht zonsopgang"
initial_state: true
trigger:
  event: sunrise
  offset: "+00:30:00"
  platform: sun
  
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: light.tuin_grondspots
      state: on

action:
  - service: light.turn_off
    data:
      entity_id: light.tuin_grondspots

  - service: notify.slack
      data:
        message: "De zon is opgekomen, de tuinlichten worden uitgezet"
