- alias: "Tuinlicht zonsondergang"
  action:
    entity_id: script.turn_on_tree_lights
    service: script.turn_on
  trigger:
    event: sunset
    platform: sun
    offset: "-00:30:00"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.state
        state: home
  initial_state: true

- alias: "Tuinlicht zonsopgang"
  action:
    entity_id: script.turn_off_tree_lights
    service: script.turn_on
  initial_state: true
  trigger:
    event: sunrise
    offset: "+00:30:00"
    platform: sun
