esphome:
  name: 433receiver
  platform: ESP8266
  board: d1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_ota_password

ota:
  password: !secret api_ota_password

remote_receiver:
  pin: D8
  dump: 
    - rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb