esphome:
  name: wemosd1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

binary_sensor:
  - platform: status
    name: "Status"